### ISSUE TITLE
"Deploy failed, please check the repo and try again"

### ISSUE THREAD

**Issue by sedubois** [zpnk/stage-ci#12]
I followed the procedure on stage.now.sh, but got this error message without further information. Any tips? This repo looks quite promising, if only it could work! 🙂 

Thanks a lot

**Comment by jimthedev** [comment]
@sedubois Are you on deploy.now.sh? I tried it that way but it wasn't working for me so I did it from the CLI instead (put in your own tokens): 

```
git clone https://github.com/zpnk/stage-ci.git
now -e GITHUB_TOKEN=11111111111111 -e ZEIT_API_TOKEN=ABCDEFG123456
```

When prompted, pick dockerfile as the start point. Once it is deployed you should be able to move forward with the instructions. Just make sure to select application/json as the content type in github's webhooks.

**Comment by jimthedev** [comment]
@sedubois specifically this is the issue: https://github.com/zpnk/deploy.now/issues/7

**Comment by zpnk** [comment]
@sedubois Sorry you ran into this, and thanks for the report!

Like @jimthedev said, this is an issue with the deploy.now service - it doesn't (yet) support deploy Docker-based projects, which stage-ci is.

Using the now CLI to deploy works, but we definitely want to get this fixed upstream so our docs aren't misleading!

There is an open PR to provide Dockerfile support on deploy.now, as soon as it is merged this issue will be fixed!

**Comment by zpnk** [comment]
zpnk/deploy.now#8 has now been merged, bringing Docker support to the deploy button! 

That should fix this issue, if it doesn't please let me know! Closing for now. :)
