### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by jimthedev** [zpnk/stage-ci#13]
Love this but would you mind adding a license? MIT or Apache2 would be ideal IMO.

**Comment by mxstbr** [comment]
The `license` property in the `package.json` is set to `"MIT"`, would still be nice to add an explicit `LICENSE` file :blush:

**Comment by jimthedev** [comment]
Ah good catch. 💯  I missed it due to personal preference. I typically look for LICENSE.md but as long as it is somewhere, that's cool. Alternatively a note in README is common.

**Comment by jimthedev** [comment]
Closing for now since any additional license would be duplicate information.

**Comment by zpnk** [comment]
I've added a more prominent license description in the readme as well as the full license in LICENSE. 

It's MIT. 😊

**Comment by jimthedev** [comment]
<3
