### ISSUE TITLE
Two PRs with same branch name but different git tree errors Stage-ci.

### ISSUE THREAD

**Issue by jimthedev** [zpnk/stage-ci#14]
If you already have a branch in your repo called, let's say `patch-1`. Stage-ci has run and deployed but we're not yet ready to merge so the PR and the deploy is still out there. This is no problem and stage-ci works wonders.

Now. Time for a bit of chaos.  Another user **with a fork of the repo** creates the same branch name but for a different issue.  She puts in a PR and of course stage-ci tries to do a deploy but it errors because there is already a different deploy with that name.

**Comment by jimthedev** [comment]
I showed it off in a dummy project here: https://github.com/jimthedev/io-bootstrap/pulls

Notice that both # 3 and # 4 are pulling the mo-betta branch but 4 is doing so from across a fork.

**Comment by hawkins** [comment]
#8 would alleviate this issue for the most part, right?

**Comment by jimthedev** [comment]
Yes I think so. Thanks!
