### ISSUE TITLE
add secret token

### ISSUE THREAD

**Issue by jimthedev** [zpnk/stage-ci#15]
It would be awesome to be able to place a secret token in stage-ci to take advantage of the webhook secret token functionality that [github offers](https://developer.github.com/webhooks/securing/).

**Comment by zpnk** [comment]
Great idea, support.

**Comment by jimthedev** [comment]
I'll take a stab at this, you can assign to me if you want.

**Comment by jimthedev** [comment]
BTW, would it be ok if this was added as required if it works? It'd be a breaking change but at the moment anyone running this has an unsecured server that someone could send a bunch of requests to and it would max out their zeit deploys.

**Comment by zpnk** [comment]
@jimthedev Thanks for tackling this! And yes, I think making it required is the way to go from a security standpoint. 👍

**Comment by jimthedev** [comment]
@zpnk @amccloud you can review the pr but please don't merge until there is a corresponding docs PR

edit: No need to wait anymore. Ready to review and merge.

**Comment by jimthedev** [comment]
@zpnk @amccloud Ok this is all set. Docs PR is done on the other repo so both should be ready to go whenever you are done reviewing.
