### ISSUE TITLE
GitHub deployment events?

### ISSUE THREAD

**Issue by creichert** [zpnk/stage-ci#17]
Really cool app. I'm in the process of settings everything up, but I have a question:

- Does **stage-ci** (or **Now**) use GitHub's deployments API to send deployment events to GitHub by chance?

I have a tool called assertible (https://github.com/integrations/assertible) that uses GitHub's deployment status events to run automated acceptance tests against staging/qa/dev/prod environments immediately after they are deployed. The end result ends up looking like this image, a **Heroku Review Apps** deployment:

![image](https://cloud.githubusercontent.com/assets/526560/25933323/44bb49da-35db-11e7-839a-1e8823acec51.png)

I'm a little new to Now so any help would be appreciated! My ultimate goal is to make sure Assertible can support stage-ci.

**Comment by zpnk** [comment]
We do not currently use the GitHub deployment api. That said, I really like the idea of having those "deployed" notifications and the "view deployment" button. 

I would support moving over to using it if possible. What are the pros/cons?

Edit: for anyone familiar with the deployment api - what would we need to change to use it?

**Comment by creichert** [comment]
@zpnk Thanks for the reply. Looks like a lot of the hard work is taken care of since the GitHub API w/ `repo` scope is already used (https://github.com/zpnk/stage-ci/blob/master/src/core.js#L101). 

Here's the API calls needed:

- [**Create a deployment**](https://developer.github.com/v3/repos/deployments/#create-a-deployment)
- [**Create deployment status**](https://developer.github.com/v3/repos/deployments/#create-a-deployment-status)

In addition to the picture I posted, you can mark deployments as "pending", "failed", "success", "inactive" which will work very well w/ `stage-ci`

---

The biggest con I can think of is that the actual "View deployment" links require a custom GitHub API media-type (`application/vnd.github.ant-man-preview+json`). This means it's technically still in developer preview. However, GitHub had  this feature out for a while and companies like Heroku are building Review Apps based on it, so I'm confident it will be supported. (_this only applies to the **View Deployment** link, the other deployments API features are supported_).

**Comment by creichert** [comment]
To expand on the implementation part of it, this looks like the main deployment logic:

```
      await setStatus('pending', 'Staging...');
      await sync(cloneUrl, localDirectory, {ref, checkout: sha});
      await stage(localDirectory, {alias});
      await setStatus('success', alias, alias);
```
Assuming it's somehow hooked into `setStatus`:

- When status is `pending`
  - POST a deployment to GitHub
  - POST a deployment status event as `pending`  (you need the `id` for the **deployment**)
- When status is success
  - POST a deployment status event as `success` (you need the `id` for the **deployment**)

That's the gist for a successful deployment. Of course if it's a failure then update the deployment w/ a deployment status of `failure`.

**Comment by mxstbr** [comment]
Oh my god I would love this feature! 😍
