### ISSUE TITLE
Cannot deploy Github branch

### ISSUE THREAD

**Issue by misterfresh** [zpnk/stage-ci#36]
Upon clicking on Deploy, nothing happens. Checking in the console, there is a request with a 500 error status code, and the body contains the message "error
:
""Response code 404 (Not Found)"""

**Comment by hugomd** [comment]
Hard to say without any other error logs, but this is likely a duplicate of #34

**Comment by zpnk** [comment]
Should be fixed in [`v1.3.0`](https://github.com/zpnk/stage-ci/releases/tag/v1.3.0).
