### ISSUE TITLE
GitLab Support

### ISSUE THREAD

**Issue by hugomd** [zpnk/stage-ci#9]
I currently self-host GitLab and use it almost exclusively, so I'd love to see support for GitLab. GitLab has its [own implementation of webhooks](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md) but it I believe it has some compatibility already with GitHub webhooks (you might be able to use a similar request body).

I'll have a look at getting it running with GitLab and make a PR if any changes need to be made.

**Comment by zpnk** [comment]
We've split a lot of the [GitHub specific logic](https://github.com/zpnk/stage-ci/blob/master/src/core.js#L75) out already, so it should be straightforward to copy that pattern into a `gitlab` method. Then, we could add a specific `/gitlab` endpoint to handle the webhook specifics. 

I don't know much about GitLab, so I'm opening this up for contributions! Shouldn't be too much work tbh!

**Comment by hugomd** [comment]
@zpnk I'm working on this, not sure when I'll have it done by though! 👍
